# Sidebar navigation

- label: 'bodyLITERATE Guidelines'
  link: '/'  
- label: Design System
  items:
    - label: 'Identity'
      link: '/guidelines/identity'
    - label: 'Typography'
      link: '/guidelines/typography'
    - label: 'Color'
      link: '/guidelines/colour'
    - label: 'Illustration'
      link: '/guidelines/illustration'
    - label: 'Motion'
      link: '/guidelines/motion'
    - label: 'Buttons'
      link: '/guidelines/buttons'